<?php
// Add an nonce field so we can check for it later.
wp_nonce_field(CMPVT_SLUG_NAME.'-custom-fields', CMPVT_SLUG_NAME.'-custom-fields-nonce');
?>

<p>
    <label for="purchase">
        <span>
            <?php _e('Product Purchase Link:', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_purchase" id="purchase" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_purchase'); ?>">
    <!--<input type="color" name="cmpvt_purchase_color" id="client-color" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_purchase_color'); ?>">-->
</p>

<p>
    <label for="link">
        <span>
            <?php _e('Product Info Link :', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_link" id="link" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_link'); ?>">
    <!--<input type="color" name="cmpvt_link_color" id="link-color" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_link_color'); ?>">-->
</p>

<p>
    <label for="add1">
        <span>
            <?php echo CMPVT_Labels::getLocalized('add1_link'); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_add1" id="add1" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_add1'); ?>">
</p>

<p>
    <label for="add2">
        <span>
            <?php echo CMPVT_Labels::getLocalized('add2_link'); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_add2" id="add2" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_add2'); ?>">
</p>

<p>
    <label for="add3">
        <span>
            <?php echo CMPVT_Labels::getLocalized('add3_link'); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_add3" id="free" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_add3'); ?>">
</p>

<p>
    <label for="add4">
        <span>
            <?php echo CMPVT_Labels::getLocalized('add4_link'); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_add4" id="video" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_add4'); ?>">
</p>

<p>
    <label for="price">
        <span>
            <?php _e('Price :', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_price" id="price" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_price', ''); ?>">
</p>

<p>
    <label for="discount">
        <span>
            <?php _e('Discount Text :', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <br>
    <input type="text" name="cmpvt_discount" id="discount" class="regular-text" value="<?php echo CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_discount'); ?>">
</p>

<p>
    <label for="newprod">
        <span>
            <?php _e('Is this a new Product:', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <input type="hidden" name="cmpvt_new_prod" value="0">
    <input type="checkbox" name="cmpvt_new_prod" id="newprod" value="1" <?php checked('1', CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_new_prod')); ?> >
</p>

<p>
    <label for="featuredprod">
        <span>
            <?php _e('Is this a Featured Product:', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <input type="hidden" name="cmpvt_featured_prod" value="0">
    <input type="checkbox" name="cmpvt_featured_prod" id="featuredprod" value="1" <?php checked('1', CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_featured_prod')); ?> >
</p>

<p>
    <label for="pauseprod"><span>
            <?php _e('Pause this Product:', CMPVT_SLUG_NAME); ?>
        </span>
    </label>
    <input type="hidden" name="cmpvt_pause_prod" value="0">
    <input type="checkbox" name="cmpvt_pause_prod" id="pauseprod" value="1" <?php checked('1', CMPluginsVideoTutorials::meta($post->ID, 'cmpvt_pause_prod')); ?>>
</p>